const data = {
  code: 0,
  result: {
    standardAdList: [
      {
        _id: "637c6f2be38504001de06522",
        gymName: "역삼 복싱인사이드짐",
        gymPhotoBig:
          "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/1849e12400722cd594/2Zw51h5efZxFRjKcZ6NmVhwrWuyBC6Z4RW7M.background_photo.jpg",
        gymPhotoSmall:
          "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/1849e12400722cd594/2Zw51h5efZxFRjKcZ6NmVhwrWuyBC6Z4RW7M.background_photo.jpg",
        address: "서울 강남구 역삼동",
        location: [127.036438, 37.4951774],
        review: {
          rate: 5,
          count: 4,
        },
        isWomenOnly: false,
        isReservationRequired: false,
        isLowestPrice: true,
        hasDailyItem: false,
        isLiked: false,
        price: {
          priceId: "a7e0fa3a-6bb4-4c18-ac6a-8b884cd07539",
          productId: "ac8787cc-0932-4684-94a9-f1a05680e78e",
          productName: "평일기간권(주5회권)",
          defaultPrice: 1920000,
          dagymPrice: 1824000,
          dagymPriceRemainingCount: 5,
          productCategory: "general",
          productType: "period",
          periodUnit: "month",
          period: 12,
          count: null,
          productTags: [
            {
              id: "66ec11ad9f965eebcf86ad85",
              name: "복싱",
            },
          ],
        },
        exhibitionRemainingCount: null,
        tags: ["복싱"],
        program: {
          free: "",
        },
        service: {
          free: "",
        },
        label: {
          title: "영상으로 운동시설을 자세히 볼 수 있어요.",
          description: "",
        },
        videoUrl: "https://youtu.be/qhQ1Ny9fCac",
        videoThumbnailUrl:
          "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/video/qhQ1Ny9fCac.mp4",
        coupons: null,
        culturalTaxDeductionRate: 0.5,
        isSportsFacilityCertified: true,
        isDagymRecommended: true,
        hasActiveHotDeal: false,
        matchedBy: null,
        matchedData: null,
        searchScore: null,
      },
    ],
    liteAdList: [
      {
        _id: "605b085443115b0039224e0a",
        gymName: "강남 아쉬탕가요가스튜디오",
        gymPhotoBig:
          "https://dgmanager.s3.ap-northeast-2.amazonaws.com/gym-photo/89325b4d-2393-4d5e-931f-8ff935bb7aed/1768284163494_d91ebbc9-9874-476b-aadd-c64594a5e488.jpg",
        gymPhotoSmall:
          "https://dgmanager.s3.ap-northeast-2.amazonaws.com/thumbnail/gym-photo/89325b4d-2393-4d5e-931f-8ff935bb7aed/1768284163494_d91ebbc9-9874-476b-aadd-c64594a5e488.jpg",
        address: "서울 서초구 서초동",
        location: [127.0285389, 37.4928036],
        review: {
          rate: 5,
          count: 35,
        },
        isWomenOnly: false,
        isReservationRequired: false,
        isLowestPrice: true,
        hasDailyItem: true,
        isLiked: false,
        price: {
          priceId: "ff29519b-9a9d-4697-92de-c7d4895493df",
          productId: "13542dc1-847b-499c-ac2e-7e15b0b7a13f",
          productName: "아쉬탕가 요가 & 빈야사 요가 (주 4회)",
          defaultPrice: 1638000,
          dagymPrice: 1457000,
          dagymPriceRemainingCount: 3,
          productCategory: "general",
          productType: "period",
          periodUnit: "month",
          period: 12,
          count: null,
          productTags: [
            {
              id: "66ec10f39f965eebcf86ad73",
              name: "요가",
            },
          ],
        },
        exhibitionRemainingCount: null,
        tags: ["요가"],
        program: {
          free: "",
        },
        service: {
          free: "️공용 락커 / ️Wi-Fi",
        },
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
        culturalTaxDeductionRate: null,
        isSportsFacilityCertified: false,
        isDagymRecommended: true,
        hasActiveHotDeal: false,
        matchedBy: null,
        matchedData: null,
        searchScore: null,
      },
      {
        _id: "68ec8dbb2ba98d21600d7b6b",
        gymName: "서초 코코필라테스",
        gymPhotoBig:
          "https://dgmanager.s3.ap-northeast-2.amazonaws.com/gym-photo/7c3d0263-8c19-4e88-8dec-740af554798b/1760421408525_01bc7e19-ff61-427f-b29e-e8184edd8585.jpg",
        gymPhotoSmall:
          "https://dgmanager.s3.ap-northeast-2.amazonaws.com/thumbnail/gym-photo/7c3d0263-8c19-4e88-8dec-740af554798b/1760421408525_01bc7e19-ff61-427f-b29e-e8184edd8585.jpg",
        address: "서울 서초구 서초동",
        location: [127.0306418, 37.4901825],
        review: {
          rate: 5,
          count: 2,
        },
        isWomenOnly: false,
        isReservationRequired: true,
        isLowestPrice: true,
        hasDailyItem: true,
        isLiked: false,
        price: {
          priceId: "9f9b9934-67aa-45c8-abaa-8d008026f514",
          productId: "a66938f6-f39a-4d25-a6ab-c1cc83e4f3d5",
          productName: "[ 2:1 ] 듀엣 or 그룹레슨 👭",
          defaultPrice: 1200000,
          dagymPrice: 1020000,
          dagymPriceRemainingCount: 3,
          productCategory: "general",
          productType: "count",
          periodUnit: "month",
          period: 3,
          count: 24,
          productTags: [
            {
              id: "66ec11939f965eebcf86ad7d",
              name: "기구필라테스",
            },
            {
              id: "66ec11929f965eebcf86ad7b",
              name: "소도구필라테스",
            },
            {
              id: "66ec11919f965eebcf86ad79",
              name: "매트필라테스",
            },
          ],
        },
        exhibitionRemainingCount: null,
        tags: ["기구필라테스"],
        program: {
          free: "",
        },
        service: {
          free: "무료주차2시간",
        },
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
        culturalTaxDeductionRate: null,
        isSportsFacilityCertified: false,
        isDagymRecommended: true,
        hasActiveHotDeal: false,
        matchedBy: null,
        matchedData: null,
        searchScore: null,
      },
      {
        _id: "58de44c46c51e93b03bf3f09",
        gymName: "교대 웨이브휘트니스",
        gymPhotoBig:
          "https://dgmanager.s3.ap-northeast-2.amazonaws.com/gym-photo/25c1c4ef-d5a3-4705-afb8-2a2501542679/1778133046330_8aae0a91-3c0a-465c-87e1-7c81a94a744b.jpg",
        gymPhotoSmall:
          "https://dgmanager.s3.ap-northeast-2.amazonaws.com/thumbnail/gym-photo/25c1c4ef-d5a3-4705-afb8-2a2501542679/1778133046330_8aae0a91-3c0a-465c-87e1-7c81a94a744b.jpg",
        address: "서울 서초구 서초동",
        location: [127.018611, 37.494827],
        review: {
          rate: 4.86,
          count: 38,
        },
        isWomenOnly: false,
        isReservationRequired: false,
        isLowestPrice: true,
        hasDailyItem: true,
        isLiked: false,
        price: {
          priceId: "cfa70ceb-ef83-4672-a660-0ab2ee7ea7cd",
          productId: "1a191216-29bd-45db-9833-8f77ef84fd1e",
          productName: "헬스 회원권(운동복+수건)/연중무휴",
          defaultPrice: 410000,
          dagymPrice: 348000,
          dagymPriceRemainingCount: 5,
          productCategory: "general",
          productType: "period",
          periodUnit: "month",
          period: 12,
          count: null,
          productTags: [
            {
              id: "66ec10269f965eebcf86ad5e",
              name: "헬스",
            },
          ],
        },
        exhibitionRemainingCount: null,
        tags: ["헬스"],
        program: {
          free: "O.T 1회(시간 조율 필요)",
        },
        service: {
          free: "주차 2시간 / 수건",
        },
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
        culturalTaxDeductionRate: 1,
        isSportsFacilityCertified: true,
        isDagymRecommended: true,
        hasActiveHotDeal: false,
        matchedBy: null,
        matchedData: null,
        searchScore: null,
      },
      {
        _id: "69256ed580f5e5dd41184398",
        gymName: "신논현역 극진가라데 강남본부",
        gymPhotoBig:
          "https://dgmanager.s3.ap-northeast-2.amazonaws.com/gym-photo/32d36df9-57ac-4c81-9161-8ace2c79a26c/1764319598254_2c8be9d7-edfc-4c62-a509-d61ded883808.jpg",
        gymPhotoSmall:
          "https://dgmanager.s3.ap-northeast-2.amazonaws.com/thumbnail/gym-photo/32d36df9-57ac-4c81-9161-8ace2c79a26c/1764319598254_2c8be9d7-edfc-4c62-a509-d61ded883808.jpg",
        address: "서울 서초구 반포동",
        location: [127.0201786, 37.5042822],
        review: {
          rate: 0,
          count: 0,
        },
        isWomenOnly: false,
        isReservationRequired: true,
        isLowestPrice: true,
        hasDailyItem: true,
        isLiked: false,
        price: {
          priceId: "523724b3-e54e-487f-aa45-45c6a44fd02e",
          productId: "95847581-421a-4da6-86d3-dc1603132f4a",
          productName: "단체 수련",
          defaultPrice: 650000,
          dagymPrice: 585000,
          dagymPriceRemainingCount: 4,
          productCategory: "general",
          productType: "count",
          periodUnit: "week",
          period: 12,
          count: 48,
          productTags: [
            {
              id: "66ec11b29f965eebcf86ad8f",
              name: "마샬아츠",
            },
          ],
        },
        exhibitionRemainingCount: null,
        tags: ["MMA"],
        program: {
          free: "",
        },
        service: {
          free: "",
        },
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
        culturalTaxDeductionRate: null,
        isSportsFacilityCertified: false,
        isDagymRecommended: true,
        hasActiveHotDeal: false,
        matchedBy: null,
        matchedData: null,
        searchScore: null,
      },
      {
        _id: "658154dbd5cd6e0063e02c95",
        gymName: "교대 소울앤바디",
        gymPhotoBig:
          "https://dgmanager.s3.ap-northeast-2.amazonaws.com/gym-photo/ef5d06aa-761b-4117-9730-70d72e03cea4/62853329e2fc4e6db63722b5e27fb557.jpg",
        gymPhotoSmall:
          "https://dgmanager.s3.ap-northeast-2.amazonaws.com/thumbnail/gym-photo/ef5d06aa-761b-4117-9730-70d72e03cea4/62853329e2fc4e6db63722b5e27fb557.jpg",
        address: "서울 서초구 서초동",
        location: [127.0150554, 37.4961801],
        review: {
          rate: 5,
          count: 6,
        },
        isWomenOnly: false,
        isReservationRequired: true,
        isLowestPrice: true,
        hasDailyItem: true,
        isLiked: false,
        price: {
          priceId: "c00b7773-bd19-48a7-a2fe-788503d4bf36",
          productId: "46271b3f-0145-4743-a911-1288e167f50d",
          productName: "🔥선착순🔥1:1 PT( +개인헬스 이용권)",
          defaultPrice: 2800000,
          dagymPrice: 2520000,
          dagymPriceRemainingCount: null,
          productCategory: "general",
          productType: "count",
          periodUnit: "month",
          period: 12,
          count: 50,
          productTags: [
            {
              id: "66ec10e09f965eebcf86ad65",
              name: "1:1P.T",
            },
          ],
        },
        exhibitionRemainingCount: null,
        tags: ["P.T"],
        program: {
          free: "주 1회 PT 진행시 개인운동 가능",
        },
        service: {
          free: "️운동복 +수건+원두커피 / ️주차 / - 오전 8시 ~ 오후 6시30분 : 1시간 30분 무료 추가 10분당 1,000원 / - 그 외 시간 : 무료",
        },
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
        culturalTaxDeductionRate: null,
        isSportsFacilityCertified: false,
        isDagymRecommended: true,
        hasActiveHotDeal: false,
        matchedBy: null,
        matchedData: null,
        searchScore: null,
      },
      {
        _id: "650a5823165b68001d550d7f",
        gymName: "서초 하이브짐",
        gymPhotoBig:
          "https://dgmanager.s3.ap-northeast-2.amazonaws.com/gym-photo/8dbc86e6-6a28-4880-9996-5db1bc7b7f06/1773639339795_77a93027-f424-41fd-a5ab-801f731106f0.jpg",
        gymPhotoSmall:
          "https://dgmanager.s3.ap-northeast-2.amazonaws.com/thumbnail/gym-photo/8dbc86e6-6a28-4880-9996-5db1bc7b7f06/1773639339795_77a93027-f424-41fd-a5ab-801f731106f0.jpg",
        address: "서울 서초구 서초동",
        location: [127.0202675, 37.4857432],
        review: {
          rate: 4.75,
          count: 20,
        },
        isWomenOnly: false,
        isReservationRequired: false,
        isLowestPrice: true,
        hasDailyItem: true,
        isLiked: false,
        price: {
          priceId: "26d2a147-8225-4422-b809-5b1bc59dfa7f",
          productId: "d8d34178-d2e3-444a-aeea-9381c5329bb6",
          productName: "헬스 회원권(운동복+수건)",
          defaultPrice: 660000,
          dagymPrice: 630000,
          dagymPriceRemainingCount: 3,
          productCategory: "general",
          productType: "period",
          periodUnit: "month",
          period: 12,
          count: null,
          productTags: [
            {
              id: "66ec10269f965eebcf86ad5e",
              name: "헬스",
            },
          ],
        },
        exhibitionRemainingCount: null,
        tags: ["P.T", "헬스"],
        program: {
          free: "",
        },
        service: {
          free: "️운동복 + 수건 / ️주차",
        },
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
        culturalTaxDeductionRate: 1,
        isSportsFacilityCertified: true,
        isDagymRecommended: true,
        hasActiveHotDeal: false,
        matchedBy: null,
        matchedData: null,
        searchScore: null,
      },
    ],
    centerList: [
      {
        _id: "617f94926bdf9700390f79b4",
        gymName: "강남 헬스보이짐X필라걸",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/17cda5c5bd9390c83d/4K7xqzbHYGoUo8ZhTgSANce63XwHZfwxDFpGKyKsyjmq.jpg",
        address: "서울 강남구 역삼동",
        location: [127.0296977538902, 37.49645977961097],
        review: {
          rate: 4.9,
          count: 216,
        },
        isWomenOnly: false,
        isReservationRequired: false,
        isLowestPrice: true,
        hasDailyItem: true,
        isLiked: false,
        price: {
          priceId: "bd4a35d8-5ad3-486e-b5a3-64b1ff147059",
          productId: "064c3c12-34f7-4f90-8c09-03fc3d1eea27",
          productName: "기구필라테스x요가(주 2회)",
          defaultPrice: 950000,
          dagymPrice: 855000,
          dagymPriceRemainingCount: null,
          productCategory: "general",
          productType: "count",
          periodUnit: "month",
          period: 12,
          count: 96,
          productTags: [
            {
              id: "66ec11939f965eebcf86ad7d",
              name: "기구필라테스",
            },
          ],
        },
        exhibitionRemainingCount: null,
        tags: ["헬스", "기구필라테스", "P.T"],
        program: {
          free: "",
        },
        service: {
          free: "",
        },
        label: null,
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
        culturalTaxDeductionRate: null,
        isSportsFacilityCertified: false,
        isDagymRecommended: false,
        hasActiveHotDeal: false,
        matchedBy: null,
        matchedData: null,
        searchScore: null,
      },
      {
        _id: "60234477bd544800390a75b1",
        gymName: "강남 미진휘트니스",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/17789c373c652dd6de/2ZwTYnGWpd2EHiwVW5cXdkK17hCoeDv96Gwc.Big_023.jpg",
        address: "서울 강남구 역삼동",
        location: [127.0285595, 37.4978265],
        review: {
          rate: 4.8,
          count: 35,
        },
        isWomenOnly: false,
        isReservationRequired: false,
        isLowestPrice: true,
        hasDailyItem: true,
        isLiked: false,
        price: {
          priceId: "19508d6b-8292-4e0c-9212-5c350102fc06",
          productId: "6f3f74c5-06cb-4cc2-9d2f-8435cce7c79f",
          productName: "헬스 회원권(운동복 포함)",
          defaultPrice: 528000,
          dagymPrice: 499000,
          dagymPriceRemainingCount: 2,
          productCategory: "general",
          productType: "period",
          periodUnit: "month",
          period: 12,
          count: null,
          productTags: [
            {
              id: "66ec10269f965eebcf86ad5e",
              name: "헬스",
            },
          ],
        },
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T"],
        program: {
          free: "무료상담 / (미진휘트니스 검색 후 네이버 무료 예약 해주세요) / 다짐에서 왔다고 말씀해주세요",
        },
        service: {
          free: "운동복 / 수건 / 샤워실 / ️ 주차 2시간 가능",
        },
        label: null,
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
        culturalTaxDeductionRate: null,
        isSportsFacilityCertified: false,
        isDagymRecommended: false,
        hasActiveHotDeal: false,
        matchedBy: null,
        matchedData: null,
        searchScore: null,
      },
      {
        _id: "63216a3c82a1c2001d150a37",
        gymName: "강남 아고라피트니스",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/1833a86fb381cdabb9/2WRYBhvE5DnQkWPiGwi29QkPuqpnruXif2ru.Big_74108894.jpg",
        address: "서울 서초구 서초동",
        location: [127.0282251073486, 37.49452190093825],
        review: {
          rate: 4.69,
          count: 13,
        },
        isWomenOnly: false,
        isReservationRequired: false,
        isLowestPrice: true,
        hasDailyItem: true,
        isLiked: false,
        price: {
          priceId: "2bb53cf8-daf3-4294-924e-baf9e8feb38f",
          productId: "b781050e-c101-4b04-8952-2361b1024279",
          productName: "[해피아워] 헬스 회원권",
          defaultPrice: 490000,
          dagymPrice: 449000,
          dagymPriceRemainingCount: 3,
          productCategory: "general",
          productType: "period",
          periodUnit: "month",
          period: 12,
          count: null,
          productTags: [
            {
              id: "66ec10269f965eebcf86ad5e",
              name: "헬스",
            },
          ],
        },
        exhibitionRemainingCount: null,
        tags: ["헬스", "필라테스", "P.T"],
        program: {
          free: "",
        },
        service: {
          free: "️수건 / ️PT 회원 수업일에 주차 무료",
        },
        label: null,
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
        culturalTaxDeductionRate: null,
        isSportsFacilityCertified: false,
        isDagymRecommended: false,
        hasActiveHotDeal: false,
        matchedBy: null,
        matchedData: null,
        searchScore: null,
      },
      {
        _id: "643e5f0f39376007c6984f50",
        gymName: "강남역 아고라필라테스",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/18793a354ab5843dac/2YCTyArGctyP7AyeG4txtgu3N5WdrQWqYinx.background_photo.jpg",
        address: "서울 서초구 서초동",
        location: [127.0282081442994, 37.49451965247242],
        review: {
          rate: 5,
          count: 1,
        },
        isWomenOnly: false,
        isReservationRequired: false,
        isLowestPrice: true,
        hasDailyItem: false,
        isLiked: false,
        price: {
          priceId: "54bf0bbc-33ca-46a0-9158-e809c123ccd7",
          productId: "12e46c1b-4955-453e-beec-af1467cab6d0",
          productName: "1:1 프라이빗 개인레슨",
          defaultPrice: 2950000,
          dagymPrice: 2950000,
          dagymPriceRemainingCount: 0,
          productCategory: "general",
          productType: "period",
          periodUnit: "month",
          period: 12,
          count: null,
          productTags: [
            {
              id: "66ec11939f965eebcf86ad7d",
              name: "기구필라테스",
            },
          ],
        },
        exhibitionRemainingCount: null,
        tags: ["기구필라테스", "필라테스"],
        program: {
          free: "",
        },
        service: {
          free: "수건, 샴푸, 바디워시",
        },
        label: null,
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
        culturalTaxDeductionRate: null,
        isSportsFacilityCertified: false,
        isDagymRecommended: false,
        hasActiveHotDeal: false,
        matchedBy: null,
        matchedData: null,
        searchScore: null,
      },
      {
        _id: "60ab879cc70b9e0039950806",
        gymName: "강남 바디스펙트럼",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/1799e09b9be187138/kXYak597zA3AMvBCfu4TL2rgEZy1LPvLmrCsjEeQ5u.jpg",
        address: "서울 서초구 서초동",
        location: [127.0282290419488, 37.49424471796314],
        review: {
          rate: 5,
          count: 7,
        },
        isWomenOnly: false,
        isReservationRequired: false,
        isLowestPrice: true,
        hasDailyItem: false,
        isLiked: false,
        price: {
          priceId: "1fbfc5a8-d208-444f-9886-415a774cef6d",
          productId: "c52172f4-f928-48ec-85db-78e105d3c01f",
          productName: "1:1 P.T",
          defaultPrice: 3000000,
          dagymPrice: 2700000,
          dagymPriceRemainingCount: 5,
          productCategory: "general",
          productType: "count",
          periodUnit: "month",
          period: 12,
          count: 60,
          productTags: [],
        },
        exhibitionRemainingCount: null,
        tags: ["P.T", "헬스"],
        program: {
          free: "1회무료체험",
        },
        service: {
          free: "운동복 / 개인라커 / 개인운동권 / 채성분측정 / 3D 체형분석기 측정 / 가족과공유가능",
        },
        label: null,
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
        culturalTaxDeductionRate: 0.5,
        isSportsFacilityCertified: true,
        isDagymRecommended: false,
        hasActiveHotDeal: false,
        matchedBy: null,
        matchedData: null,
        searchScore: null,
      },
      {
        _id: "60bf16b4c70b9e0039959a44",
        gymName: "강남역 로그짐",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/179ea70affa41df064/2YUe3g3ZvG7JKoGMCJUXL3kHds7HUAyX6aQb.background_photo.jpg",
        address: "서울 서초구 서초동",
        location: [127.0264046, 37.4983153],
        review: {
          rate: 0,
          count: 0,
        },
        isWomenOnly: false,
        isReservationRequired: false,
        isLowestPrice: true,
        hasDailyItem: true,
        isLiked: false,
        price: {
          priceId: "edae3c19-f616-4353-b5b4-4dc30e75b699",
          productId: "dec9f0ee-235c-4f7f-a068-a02ff89e837c",
          productName: "오우진 트레이너 1:1 P.T ",
          defaultPrice: 4000000,
          dagymPrice: 3600000,
          dagymPriceRemainingCount: 5,
          productCategory: "general",
          productType: "count",
          periodUnit: "month",
          period: 12,
          count: 100,
          productTags: [
            {
              id: "66ec10269f965eebcf86ad5e",
              name: "헬스",
            },
          ],
        },
        exhibitionRemainingCount: null,
        tags: ["P.T"],
        program: {
          free: "",
        },
        service: {
          free: "운동복 / 수건 / Wi-fi / 주차 (기계식 주차 / SUV 뒷건물)",
        },
        label: null,
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
        culturalTaxDeductionRate: null,
        isSportsFacilityCertified: false,
        isDagymRecommended: false,
        hasActiveHotDeal: false,
        matchedBy: null,
        matchedData: null,
        searchScore: null,
      },
      {
        _id: "6667dc6d6a36af001d86efb7",
        gymName: "강남 와이짐 ",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/19005b50c7638d4f88/2YC561ErSrJJDCmXjri6nmVZeAyZeMjbUMRA.센터 Big 복사.jpg",
        address: "서울 서초구 서초동",
        location: [127.0291599061871, 37.49207994460832],
        review: {
          rate: 0,
          count: 0,
        },
        isWomenOnly: false,
        isReservationRequired: true,
        isLowestPrice: false,
        hasDailyItem: false,
        isLiked: false,
        price: {
          priceId: "ee30ebc4-c9d0-46f5-8184-4d4d25c5b76d",
          productId: "cee3740a-dd11-414a-b3fd-ea70911ec21f",
          productName: "PT Sessions",
          defaultPrice: 2750000,
          dagymPrice: 2750000,
          dagymPriceRemainingCount: 0,
          productCategory: "general",
          productType: "count",
          periodUnit: "day",
          period: 180,
          count: 50,
          productTags: [],
        },
        exhibitionRemainingCount: null,
        tags: ["P.T"],
        program: {
          free: "",
        },
        service: {
          free: "주차 : 2시간 무료 / 샤워용품",
        },
        label: null,
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
        culturalTaxDeductionRate: null,
        isSportsFacilityCertified: false,
        isDagymRecommended: false,
        hasActiveHotDeal: false,
        matchedBy: null,
        matchedData: null,
        searchScore: null,
      },
      {
        _id: "6271fc76df6c66001d16599f",
        gymName: "강남 피트니스에비뉴&필라테스",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/1808d422ff54518890/4K8ftS1mYaMv5V9KzZPSrRF5iUirQyhThR38GzUUEfsm.jpg",
        address: "서울 강남구 역삼동",
        location: [127.0311244361704, 37.49161091956967],
        review: {
          rate: 5,
          count: 6,
        },
        isWomenOnly: false,
        isReservationRequired: false,
        isLowestPrice: false,
        hasDailyItem: false,
        isLiked: false,
        price: {
          priceId: "3d78b4be-0898-4ff6-b963-47dd8b32630e",
          productId: "ee821ba4-3377-4e4b-a79a-f1993ca8ad7f",
          productName: "1:1 PT&필라테스",
          defaultPrice: 1980000,
          dagymPrice: 1980000,
          dagymPriceRemainingCount: 0,
          productCategory: "general",
          productType: "count",
          periodUnit: "month",
          period: 1,
          count: 30,
          productTags: [],
        },
        exhibitionRemainingCount: null,
        tags: ["P.T", "기구필라테스"],
        program: {
          free: "OT 인바디 상담",
        },
        service: {
          free: "운동복 / 주차 : 3시간 무료",
        },
        label: null,
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
        culturalTaxDeductionRate: null,
        isSportsFacilityCertified: false,
        isDagymRecommended: false,
        hasActiveHotDeal: false,
        matchedBy: null,
        matchedData: null,
        searchScore: null,
      },
      {
        _id: "66dd8ff301d0e4001ddafbba",
        gymName: "강남 알파짐",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/191d17a4e963fd287b/Lsc7rQY3Xcv6b1G9FrYmfc3UynNLCWhrBA.Big_241018_강남_PT알파짐_01.jpg",
        address: "서울 강남구 역삼동",
        location: [127.0315541532365, 37.49166937105838],
        review: {
          rate: 5,
          count: 7,
        },
        isWomenOnly: false,
        isReservationRequired: false,
        isLowestPrice: true,
        hasDailyItem: true,
        isLiked: false,
        price: {
          priceId: "752dc787-24b9-40ed-8b0a-b7a5fa32df0e",
          productId: "232d0a63-3aa8-4e78-aefa-a799d16a35a1",
          productName: "1:1 PT (다짐 특가)",
          defaultPrice: 2475000,
          dagymPrice: 2227500,
          dagymPriceRemainingCount: 2,
          productCategory: "general",
          productType: "count",
          periodUnit: "month",
          period: 8,
          count: 50,
          productTags: [
            {
              id: "66ec10e09f965eebcf86ad65",
              name: "1:1P.T",
            },
          ],
        },
        exhibitionRemainingCount: null,
        tags: ["P.T", "헬스"],
        program: {
          free: "",
        },
        service: {
          free: "샤워",
        },
        label: null,
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
        culturalTaxDeductionRate: null,
        isSportsFacilityCertified: false,
        isDagymRecommended: false,
        hasActiveHotDeal: false,
        matchedBy: null,
        matchedData: null,
        searchScore: null,
      },
      {
        _id: "62c6889c3289ee001dbf89aa",
        gymName: "서초 필라테스이즘 강남역점",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/181d785a1dc51d8fc7/4K8g83TbiKmesJZodCJvsSchpEPNaCH4UBvzTqXs8smy.jpg",
        address: "서울 서초구 서초동",
        location: [127.029348988698, 37.49125547604471],
        review: {
          rate: 5,
          count: 7,
        },
        isWomenOnly: false,
        isReservationRequired: false,
        isLowestPrice: false,
        hasDailyItem: true,
        isLiked: false,
        price: {
          priceId: "90927b70-32ea-4ae6-acb9-0187d6be7dc3",
          productId: "c404987d-bcba-49ad-b808-64362b66897a",
          productName: "그룹필라테스(4:1)",
          defaultPrice: 600000,
          dagymPrice: 600000,
          dagymPriceRemainingCount: 0,
          productCategory: "general",
          productType: "count",
          periodUnit: "month",
          period: 3,
          count: 24,
          productTags: [],
        },
        exhibitionRemainingCount: null,
        tags: ["필라테스", "기구필라테스"],
        program: {
          free: "",
        },
        service: {
          free: "공용락커 / 주차 2시간 가능",
        },
        label: null,
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
        culturalTaxDeductionRate: null,
        isSportsFacilityCertified: false,
        isDagymRecommended: false,
        hasActiveHotDeal: false,
        matchedBy: null,
        matchedData: null,
        searchScore: null,
      },
      {
        _id: "672aefa7a49abf001dd7569f",
        gymName: "서초 로얄핏PT",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/192ffb8256f57b4b34/2ZxkeckkKqyesr8Zs9jVnFfxCUFVK7wjLvTv.background_photo.jpg",
        address: "서울 서초구 서초동",
        location: [127.0258552393305, 37.49216180471107],
        review: {
          rate: 0,
          count: 0,
        },
        isWomenOnly: false,
        isReservationRequired: true,
        isLowestPrice: true,
        hasDailyItem: true,
        isLiked: false,
        price: {
          priceId: "1919fd69-1459-4413-9399-9410649c0f00",
          productId: "6a4f1ab9-221e-412e-8624-0d52a16d56b0",
          productName: "1:1 PT",
          defaultPrice: 1089000,
          dagymPrice: 1089000,
          dagymPriceRemainingCount: 0,
          productCategory: "general",
          productType: "count",
          periodUnit: "month",
          period: 3,
          count: 20,
          productTags: [],
        },
        exhibitionRemainingCount: null,
        tags: ["P.T"],
        program: {
          free: "",
        },
        service: {
          free: "주차 2시간 무료, 운동복,수건 제공",
        },
        label: null,
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
        culturalTaxDeductionRate: 0.5,
        isSportsFacilityCertified: true,
        isDagymRecommended: false,
        hasActiveHotDeal: false,
        matchedBy: null,
        matchedData: null,
        searchScore: null,
      },
      {
        _id: "6967197202334e98ba07feb5",
        gymName: "역삼 소울업짐",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://dgmanager.s3.ap-northeast-2.amazonaws.com/thumbnail/gym-photo/9b367a23-8f67-4b60-97be-7dfc84986693/1770703924963_4cf40388-da95-4616-acf5-f3149cf3d992.jpg",
        address: "서울 강남구 역삼동",
        location: [127.0359376, 37.4992741],
        review: {
          rate: 5,
          count: 51,
        },
        isWomenOnly: false,
        isReservationRequired: false,
        isLowestPrice: true,
        hasDailyItem: true,
        isLiked: false,
        price: {
          priceId: "a5683a09-e29e-4a67-904d-d9eff34a8a5e",
          productId: "f6a4cb4c-0770-4801-bfaf-63097d19d398",
          productName: "소울업짐 회원권",
          defaultPrice: 270000,
          dagymPrice: 165000,
          dagymPriceRemainingCount: 5,
          productCategory: "general",
          productType: "period",
          periodUnit: "month",
          period: 6,
          count: null,
          productTags: [
            {
              id: "66ec10269f965eebcf86ad5e",
              name: "헬스",
            },
          ],
        },
        exhibitionRemainingCount: null,
        tags: ["헬스"],
        program: {
          free: "",
        },
        service: {
          free: "",
        },
        label: null,
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
        culturalTaxDeductionRate: 1,
        isSportsFacilityCertified: true,
        isDagymRecommended: false,
        hasActiveHotDeal: false,
        matchedBy: null,
        matchedData: null,
        searchScore: null,
      },
      {
        _id: "6449b16a8ec65b001d381ef0",
        gymName: "역삼 엑스퍼티짐",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://dgmanager.s3.ap-northeast-2.amazonaws.com/thumbnail/gym-photo/8d69f48d-62d8-4f7f-9a61-506e3718af2a/1745562598865_5edf95ea-2d91-4abd-972b-7f473128c0dc.jpg",
        address: "서울 강남구 역삼동",
        location: [127.0348231, 37.5009438],
        review: {
          rate: 4.82,
          count: 17,
        },
        isWomenOnly: false,
        isReservationRequired: false,
        isLowestPrice: true,
        hasDailyItem: true,
        isLiked: false,
        price: {
          priceId: "d3548967-8b83-4c2b-a410-98f71c483bc4",
          productId: "2252a0a6-00b2-4df8-9ef8-d1465b330947",
          productName: "1:1 P.T 2회+헬스장 7일 이용권",
          defaultPrice: 39900,
          dagymPrice: 39900,
          dagymPriceRemainingCount: 0,
          productCategory: "general",
          productType: "count",
          periodUnit: "day",
          period: 7,
          count: 2,
          productTags: [
            {
              id: "66ec10e09f965eebcf86ad65",
              name: "1:1P.T",
            },
            {
              id: "66ec10269f965eebcf86ad5e",
              name: "헬스",
            },
          ],
        },
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T", "골프"],
        program: {
          free: "",
        },
        service: {
          free: "️운동복 + 수건 / ️골프회원권 등록시 주차1시간무료 / ️아메리카노(스타벅스원두)",
        },
        label: null,
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
        culturalTaxDeductionRate: 1,
        isSportsFacilityCertified: true,
        isDagymRecommended: false,
        hasActiveHotDeal: false,
        matchedBy: null,
        matchedData: null,
        searchScore: null,
      },
      {
        _id: "63ea00157077ec001d47b7d5",
        gymName: "역삼 무니요가",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://dgmanager.s3.ap-northeast-2.amazonaws.com/thumbnail/gym-photo/5147c65b-8f9d-40ba-915e-46204d434307/1763104473103_0e628639-2eb3-4a72-929b-21f1225717dd.png",
        address: "서울 강남구 역삼동",
        location: [127.0370192, 37.4986776],
        review: {
          rate: 5,
          count: 9,
        },
        isWomenOnly: false,
        isReservationRequired: false,
        isLowestPrice: true,
        hasDailyItem: true,
        isLiked: false,
        price: {
          priceId: "393c8859-fa28-4bb7-976c-88f9da023f79",
          productId: "e86dbb24-e285-471e-849a-b80b9109bf96",
          productName: "(🔥특가) 오전에만 하고 싶어요!",
          defaultPrice: 280000,
          dagymPrice: 130000,
          dagymPriceRemainingCount: 4,
          productCategory: "general",
          productType: "count",
          periodUnit: "week",
          period: 8,
          count: 8,
          productTags: [
            {
              id: "66ec10f39f965eebcf86ad73",
              name: "요가",
            },
          ],
        },
        exhibitionRemainingCount: null,
        tags: ["요가"],
        program: {
          free: "",
        },
        service: {
          free: "공용 락커/ 매트 및 물품",
        },
        label: null,
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
        culturalTaxDeductionRate: null,
        isSportsFacilityCertified: false,
        isDagymRecommended: false,
        hasActiveHotDeal: false,
        matchedBy: null,
        matchedData: null,
        searchScore: null,
      },
      {
        _id: "65e9ad73b2e9a2001dc0737b",
        gymName: "서초 비헬씨",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://dgmanager.s3.ap-northeast-2.amazonaws.com/thumbnail/gym-photo/16f74639-5bd1-4659-a7a3-ac6c5c48cf1e/1740906530197_7f4a8e2d-88a2-402a-9b52-9250cae40162.JPG",
        address: "서울 서초구 서초동",
        location: [127.0306546, 37.4901379],
        review: {
          rate: 5,
          count: 1,
        },
        isWomenOnly: false,
        isReservationRequired: false,
        isLowestPrice: true,
        hasDailyItem: true,
        isLiked: false,
        price: {
          priceId: "4b0f8292-2e2d-4bf7-b4ea-09ecc4c79341",
          productId: "aabd8ec4-3add-4af1-a931-eb4c11e60e0f",
          productName: "헬스 회원권",
          defaultPrice: 328900,
          dagymPrice: 328900,
          dagymPriceRemainingCount: 0,
          productCategory: "general",
          productType: "period",
          periodUnit: "month",
          period: 12,
          count: null,
          productTags: [
            {
              id: "66ec10269f965eebcf86ad5e",
              name: "헬스",
            },
          ],
        },
        exhibitionRemainingCount: null,
        tags: ["헬스"],
        program: {
          free: "OT 1회",
        },
        service: {
          free: "️시설 이용 / ️운동복, 수건 / ️주차 2시간",
        },
        label: null,
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
        culturalTaxDeductionRate: null,
        isSportsFacilityCertified: false,
        isDagymRecommended: false,
        hasActiveHotDeal: false,
        matchedBy: null,
        matchedData: null,
        searchScore: null,
      },
      {
        _id: "5a227c84cde07d5b3016044c",
        gymName: "역삼 강남 챌린지다이어트 복싱",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://dgmanager.s3.ap-northeast-2.amazonaws.com/thumbnail/gym-photo/9bf241c1-13ee-4bbf-b325-9ffbb9328569/1747380980017_f2e43f70-e6bf-4caa-b4d5-00dd71dc14df.jpg",
        address: "서울 강남구 역삼동",
        location: [127.034996, 37.501572],
        review: {
          rate: 4.8,
          count: 5,
        },
        isWomenOnly: false,
        isReservationRequired: false,
        isLowestPrice: true,
        hasDailyItem: true,
        isLiked: false,
        price: {
          priceId: "d2d62b85-0135-4464-87a9-d44ed41c6a74",
          productId: "6c843ff0-2727-4867-9124-ab903063c38d",
          productName: "복싱 회원권(수건+공용글로브)",
          defaultPrice: 1500000,
          dagymPrice: 1350000,
          dagymPriceRemainingCount: null,
          productCategory: "general",
          productType: "period",
          periodUnit: "month",
          period: 12,
          count: null,
          productTags: [
            {
              id: "66ec11ad9f965eebcf86ad85",
              name: "복싱",
            },
          ],
        },
        exhibitionRemainingCount: null,
        tags: ["복싱"],
        program: {
          free: "복싱GX / 헬스 / 스킷 / 크로스핏",
        },
        service: {
          free: "수건 / 공용 글러브 대여",
        },
        label: null,
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
        culturalTaxDeductionRate: null,
        isSportsFacilityCertified: false,
        isDagymRecommended: false,
        hasActiveHotDeal: false,
        matchedBy: null,
        matchedData: null,
        searchScore: null,
      },
      {
        _id: "65bb53ee185776001dbbd72a",
        gymName: "역삼 FL GYM",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/18d63bfdd4243fb8d2/2YWaYTtpqp6Zz4gLpLs44FcnP5a1RqWKRiCa.Big_DSC03098.jpg",
        address: "서울 강남구 역삼동",
        location: [127.0379277346257, 37.49501023314936],
        review: {
          rate: 4.81,
          count: 58,
        },
        isWomenOnly: false,
        isReservationRequired: false,
        isLowestPrice: true,
        hasDailyItem: true,
        isLiked: false,
        price: {
          priceId: "9626ad4d-bffb-455a-bbd7-88658d5b5c8e",
          productId: "fef808f3-0649-4779-8fc7-8642ad958c2b",
          productName: "헬스 회원권",
          defaultPrice: 320000,
          dagymPrice: 304000,
          dagymPriceRemainingCount: 3,
          productCategory: "general",
          productType: "period",
          periodUnit: "month",
          period: 10,
          count: null,
          productTags: [
            {
              id: "66ec10269f965eebcf86ad5e",
              name: "헬스",
            },
          ],
        },
        exhibitionRemainingCount: null,
        tags: ["헬스"],
        program: {
          free: "",
        },
        service: {
          free: "️주차 : 60분 무료(추가 30분당 1,000원)",
        },
        label: null,
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
        culturalTaxDeductionRate: 1,
        isSportsFacilityCertified: true,
        isDagymRecommended: false,
        hasActiveHotDeal: false,
        matchedBy: null,
        matchedData: null,
        searchScore: null,
      },
      {
        _id: "67e636970486a55a34509168",
        gymName: "역삼 펀치박스 복싱 스튜디오",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://dgmanager.s3.ap-northeast-2.amazonaws.com/thumbnail/gym-photo/568783a7-06ba-47f0-a327-a14c0c3bf68e/1745392929073_30037f42-c45a-4c55-8a6e-4563b570e685.jpg",
        address: "서울 강남구 역삼동",
        location: [127.0338242, 37.4904722],
        review: {
          rate: 5,
          count: 2,
        },
        isWomenOnly: false,
        isReservationRequired: false,
        isLowestPrice: true,
        hasDailyItem: true,
        isLiked: false,
        price: {
          priceId: "7cdce496-7caf-4582-aaa1-08b6a624462f",
          productId: "289ba4ee-def1-40e2-9b6a-bfed4081da0f",
          productName: "[개인레슨] 1:1 피티",
          defaultPrice: 1200000,
          dagymPrice: 1020000,
          dagymPriceRemainingCount: 5,
          productCategory: "general",
          productType: "count",
          periodUnit: "month",
          period: 6,
          count: 30,
          productTags: [
            {
              id: "66ec11ad9f965eebcf86ad85",
              name: "복싱",
            },
            {
              id: "66ec10e09f965eebcf86ad65",
              name: "1:1P.T",
            },
            {
              id: "66ec163b9f965eebcf86adf1",
              name: "기타",
            },
          ],
        },
        exhibitionRemainingCount: null,
        tags: ["복싱"],
        program: {
          free: "OT 1회",
        },
        service: {
          free: "일일락커 / 수건 / 샤워시설 및 어메니티",
        },
        label: null,
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
        culturalTaxDeductionRate: null,
        isSportsFacilityCertified: false,
        isDagymRecommended: false,
        hasActiveHotDeal: false,
        matchedBy: null,
        matchedData: null,
        searchScore: null,
      },
      {
        _id: "652ca1cb8d5c02001d3d2ea9",
        gymName: "역삼 수트짐",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/18b36580320231d4e1/2YAsM4YzbHcZmyKB5oAwCFZmPdTqFf7DuTe9.background_photo.jpg",
        address: "서울 강남구 역삼동",
        location: [127.035624, 37.5015928],
        review: {
          rate: 4.67,
          count: 3,
        },
        isWomenOnly: false,
        isReservationRequired: false,
        isLowestPrice: true,
        hasDailyItem: true,
        isLiked: false,
        price: {
          priceId: "40b3f0b8-f97a-4c32-8b0e-1d3ae88122a2",
          productId: "d34582f0-37fa-42d8-a395-21e3b38853dc",
          productName: "헬스 회원권",
          defaultPrice: 520000,
          dagymPrice: 500000,
          dagymPriceRemainingCount: 3,
          productCategory: "general",
          productType: "period",
          periodUnit: "month",
          period: 12,
          count: null,
          productTags: [
            {
              id: "66ec10269f965eebcf86ad5e",
              name: "헬스",
            },
          ],
        },
        exhibitionRemainingCount: null,
        tags: ["헬스"],
        program: {
          free: "",
        },
        service: {
          free: "수건",
        },
        label: null,
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
        culturalTaxDeductionRate: null,
        isSportsFacilityCertified: false,
        isDagymRecommended: false,
        hasActiveHotDeal: false,
        matchedBy: null,
        matchedData: null,
        searchScore: null,
      },
      {
        _id: "661c5a245e60cd001d05f442",
        gymName: "강남 굿피티",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/18edec01cea2ce30ee/2WP8FNvLZdxrR4o6Ck7TWppMkLFbZzoukKJD.background_photo.jpg",
        address: "서울 강남구 도곡동",
        location: [127.0333173046618, 37.48975424603641],
        review: {
          rate: 0,
          count: 0,
        },
        isWomenOnly: false,
        isReservationRequired: false,
        isLowestPrice: false,
        hasDailyItem: true,
        isLiked: false,
        price: {
          priceId: "ad948181-bf21-478e-8c39-7fedb295c27c",
          productId: "16a7f74f-1e77-4483-bfbb-98701a52fca4",
          productName: "헬스 회원권",
          defaultPrice: 720000,
          dagymPrice: 720000,
          dagymPriceRemainingCount: 0,
          productCategory: "general",
          productType: "period",
          periodUnit: "month",
          period: 12,
          count: null,
          productTags: [
            {
              id: "66ec10269f965eebcf86ad5e",
              name: "헬스",
            },
          ],
        },
        exhibitionRemainingCount: null,
        tags: ["헬스"],
        program: {
          free: " / ",
        },
        service: {
          free: "️수건 / ️운동복 / ️PT 회원 주차 / ",
        },
        label: null,
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
        culturalTaxDeductionRate: null,
        isSportsFacilityCertified: false,
        isDagymRecommended: false,
        hasActiveHotDeal: false,
        matchedBy: null,
        matchedData: null,
        searchScore: null,
      },
    ],
  },
};

// 1. 센터리스트에서 여성 전용 헬스장만 뽑기
const newData = data.result.centerList.map((x) => {
  if (x.isWomenOnly) {
    return x;
  }
  return null;
});

console.log(newData);
// 2. 가격이 30만원 이하만 뽑기
const newData1 = data.result.centerList.map((x) => {
  if (x.price.defaultPrice <= 300000) {
    return x;
  }
  return null;
});

console.log(newData1);
// 3. 무료 주차 가능한곳 뽑기
const newData2 = data.result.centerList.map((x) => {
  if (x.service.free.includes("주차") && x.service.free.includes("무료")) {
    return x;
  }
  return null;
});

console.log(newData2);
